### ISSUE TITLE
Annoying [13:51:55] WARNING: not removing hydrogen atom with dummy atom neighbors

### ISSUE THREAD

**Issue by ale94mleon** [DrrDom/crem#14]
Hi, excellent package! I just wondering how to stop the warning message that pops up during link_mol and mutate_mol. I tried some
```python
import warnings
warnings.filterwarnings("ignore", message='not removing hydrogen atom with dummy atom neighbors')
```
without succes.

**Comment by DrrDom** [comment]
Thank you!
Warnings should be disabled at the RDKit level. More details are here https://github.com/rdkit/rdkit/issues/2683.
