### ISSUE TITLE
fragmentation problem

### ISSUE THREAD

**Issue by suice07** [DrrDom/crem#17]
Hi,

I am trying to build my own db according to the instructions, but when I try `mols = list(mutate_mol(m, db_name='test.db', max_size=3))` in the tutorial with my own db, the result list of `mols` is always empty, but when I try with the preproduced db `replacements02_sa2.db` there is no problem; I used the `CHEMBL231.smi` file in the example folder, and follow the instructions 
```
fragmentation -i CHEMBL231.smi -o frags.txt -c 32 -v
frag_to_env -i frags.txt -o r3.txt -r 3 -c 32 -v
sort r3.txt | uniq -c > r3_c.txt
env_to_db -i r3_c.txt -o tert.db -r 3 -c -v
```
got the result
```
 root@872fabd400c3:/home/crem# python test.py
[]

```
is there something iI missed?

**Comment by DrrDom** [comment]
Hi,
the described workflow seems OK with the exception of DB name (tert.db instead of test.db). If everything else is correct the issue may be in the structure of your molecule `m` - it may happen that it has all contexts of radius 3 which are not available in the test.db (for such a small DB it is possible). Try to generate DB with radius 2 or 1, would it help or not?

**Comment by suice07** [comment]
Hi,

I tried to generate db using radius 2 or 1, but when they are finished and excute ```mols = list(mutate_mol(m, db_name='test.db', max_size=3))```, there occurs some error 
```
 File "test.py", line 13, in <module>
    mols = list(mutate_mol(m, db_name='zink.db', max_size=2))
  File "/home/crem/crem/crem.py", line 487, in mutate_mol
    for frag_sma, core_sma, freq, ids in __gen_replacements(mol1=mol, mol2=None, db_name=db_name, radius=radius,
  File "/home/crem/crem/crem.py", line 344, in __gen_replacements
    row_ids = __get_replacements_rowids(cur, env, dist, min_atoms, max_atoms, radius, min_freq, **kwargs)
  File "/home/crem/crem/crem.py", line 286, in __get_replacements_rowids
    db_cur.execute(sql)
sqlite3.OperationalError: no such table: radius3
```
I don't get it, why it is still searching for the raduis3 table, is there some cache that I missed?

**Comment by DrrDom** [comment]
You have to pass a variable `radius=2` in `mutate_mol` function.
Just a tip: you may store tables with different radius in the same DB.

**Comment by suice07** [comment]
oh, sorry. I tried with radius =2, it is working,maybe with such a small db,radius =3 is too much .Thanks so much for the help!!

**Comment by suice07** [comment]
![image](https://user-images.githubusercontent.com/18343237/201248310-eacec96e-ba38-4cd9-ab99-b8133ef9e90d.png)
sorry to bother, I have some other problems while using the mutate, the original molecule looks like above, smiles format in 'NC(=N)c4ccc3[nH]c(c2cc(Cl)cc(c1cccc(N)c1)c2O)nc3c4',I set the protected ids to `[9, 10, 11, 12, 13, 14, 22, 23]`,
![image](https://user-images.githubusercontent.com/18343237/201248615-8707cb56-0004-4a5b-9225-a99995f1b177.png)
so, theoretically the marked part will stay the same. 
![image](https://user-images.githubusercontent.com/18343237/201248840-e0c85b93-8ab8-4a88-a2b7-b426cf5d120f.png)
but I got a lot of results like this, but 
![image](https://user-images.githubusercontent.com/18343237/201250580-3d269aa5-afb4-4c2b-978c-624ecdb167ce.png)
this part has never been changed. I set the radius to 3

**Comment by DrrDom** [comment]
- if some part of a molecule is never changed this can be due to absence of fragments with the same context in your DB. Reduce the context radius and run again.
- if some protected atoms are changed, most probably you choose wrong atom ids. Paste the whole code to reproduce the issue, because atom ids in rdkit will depend on how you load a molecule.
