### ISSUE TITLE
error of enumerate_compounds function

### ISSUE THREAD

**Issue by MachineGUN001** [DrrDom/crem#23]
Hi, Crem,

I tried the new function `enumerate_compounds` in `utils` module.

but there is an error, when I use the method to repeat the example you provied.
https://github.com/DrrDom/crem/commit/73dd185eb0d826b28e822bd6e55e9b31afb6632c

```
TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
```
my PC memory is 32G, so I didnot why this error occurs
could you please provide some suggesions to fix it? many thanks,

Shengyang

**Comment by DrrDom** [comment]
Did you run exactly that code from the example with a proper path to a fragment DB? If you change settings you may occur combinatorial explosion and out of memory issues.
More details are here https://github.com/DrrDom/crem/issues/22

I cannot guess what could be other causes of such an issue. Segmentation fault is always difficult to debug.

**Comment by MachineGUN001** [comment]
many thanks for your feedbacks and providing the clue for this issue.

also thank @AlanTanKX's suggestions.

set the n_iterations as less than 4 or 5, which can avoid the out use of memory.

will close the issue.

**Comment by DrrDom** [comment]
You may also reduce `max_replacements` to reduce the total number of enumerated compounds

**Comment by MachineGUN001** [comment]
> You may also reduce `max_replacements` to reduce the total number of enumerated compounds

for another thing, recommend to implement this function on linux system rather than windows os, which is easy to use out the memory on windows
