### ISSUE TITLE
Fragmentation

### ISSUE THREAD

**Issue by rajathsalegame** [DrrDom/crem#3]
Was a bit confused by the `fragment_mol` method in `fragmentation.py`, specifically these lines:

```
frags = rdMMPA.FragmentMol(mol, pattern="[!#1]!@!=!#[!#1]", maxCuts=4, resultsAsMols=False, maxCutBonds=30)
frags += rdMMPA.FragmentMol(mol, pattern="[!#1]!@!=!#[!#1]", maxCuts=3, resultsAsMols=False, maxCutBonds=30)
```

1. Shouldn't maxCuts=3 be included as a subset of all fragmentations for maxCuts=4?

2. What exactly is the difference between maxCutBonds and maxCuts? I tried looking for documentation on this and was unfortunately unable to find it.

3. Would it make more sense for the maxCuts parameter to be user-defined rather than preset? 

Thanks for your help!

**Comment by DrrDom** [comment]
MMPA rdkit module is not well documented (https://www.rdkit.org/docs/source/rdkit.Chem.rdMMPA.html), but it is easy to understand these options and investigate its behavior on simple examples.

1. Fragments outputted with maxCuts = 3 is not a subset of fragments obtained with maxCuts = 4. This is a bug of this rdkit function (https://github.com/rdkit/rdkit/issues/3040). Therefore, I produce two sets of fragments for maxCuts 3 and 4, combine them and remove duplicated fragmentations.

2. If a molecule will contain the number of bonds matching the given pattern more than maxCutBonds value this molecule will not be fragmented and will be skipped. Limiting maxCutBonds allows to avoid a combinatorial explosion. maxCuts determines how many simultaneous attachment points can be in a fragment.

3. That is possible but I do not see much advantages from this. Choosing a greater number of cuts will result in a greater number of distinct context-fragment pairs and will substantially increase database size that can become impractical to manage. But this will allow to make replacement of heavily substituted scaffolds in one step (mutation). For example a five substituted benzene ring cannot be replaced with another fragment in one step. However, in optimization tasks this can be reached in three steps, e.g. replacement of one substituent with H, replacement of a benzene fragment with an appropriate one from a database and then replacement of H with the given substituent. I do not think that fragmentation with greater maxCuts will substantially improve practical applications and scenarios used for chemical space exploration. For example in Guacamol CReM behalves comparably well relative to all other methods which give much more freedom in structure perturbation (GA Graph, EvoMol, etc). So, I consider the chosen maxCuts value as a reasonable trade-off between a database size and quality of chemical space coverage.

**Comment by rajathsalegame** [comment]
Thanks! Yes, this makes a lot of sense. I appreciate your response.

**Comment by rajathsalegame** [comment]
Sorry, I was investigating the behavior of rdMMPA and was confused what you mean by "maxCuts determines how many simultaneous attachment points can be in a fragment.". For example, even when I choose maxCuts=4, there is still only 1 attachment point in the output fragments...Also, for many of the compounds it appears core appears to be empty? Why is this the case?

Sorry for my questions--a bit new to cheminformatics, but thank you for your patience :)

**Comment by DrrDom** [comment]
Questions regarding rdkit would be better to ask in the rdkit mailing list. You may also search the previous questions and answers. Moreover, without a particular example it is difficult to understand what happened in your case.
RDKit fragmentation with maxCuts=N cuts 1, 2 and N bonds simultaneously, if possible. This result in fragments with 1, 2 and N attachment points. It tries to cut all possible combination of bonds which matched by a pattern. For example, in ethane there is no possibility to get a fragment with two attachment points if hydrogens were omitted.
Core in terms of rdMMPA is a fragment with two or more attachment points. It appears if one cuts two bonds simultaneous. If only one bond was cut the core will be empty. In this case each of two obtained fragments is considered as a core sequentially.
